drop function if exists avgAbs;
drop function if exists maxAbs;
drop function if exists rmsPop;
drop function if exists p2pPop;
drop function if exists crestFactorPop;
drop function if exists clearenceFactorPop;
drop function if exists shapFactorPop;
drop function if exists impulsePop;
create function if not exists avgAbs AS (xs)->sum(abs(xs)) / count(xs);
create function if not exists maxAbs AS (xs)->max(abs(xs));
create function if not exists rmsPop AS (xs)->sqrt(sum(xs * xs) / count(xs));
create function if not exists p2pPop AS (xs)->abs(max(xs)) + abs(min(xs));
create function if not exists crestFactorPop AS (xs)->maxAbs(xs) / rmsPop(xs);
create function if not exists clearenceFactorPop AS (xs)->pow(sum(sqrt(abs(xs))) / count(xs), 2);
create function if not exists shapFactorPop AS (xs)->rmsPop(xs) / avgAbs(xs);
create function if not exists impulsePop AS (xs)->maxAbs(xs) / avgAbs(xs);