select toYear(pickup_datetime) as year,
    toWeek(pickup_datetime) as week,
    toDayOfWeek(pickup_datetime) as day,
    toHour(pickup_datetime) as hour,
    count(*) as count_dayofweek,
    avg(trip_duration) as avg_trip_duration,
    avg(trip_distance) as avg_trip_distance,
    avg(fare_amount) as avg_fare_amount,
    avg(tip_amount) as avg_tip_amount,
    avg(total_amount) as avg_total_amount,
    sum(trip_duration) as sum_trip_duration,
    sum(trip_distance) as sum_trip_distance,
    sum(fare_amount) as sum_fare_amount,
    sum(tip_amount) as sum_tip_amount,
    sum(total_amount) as sum_total_amount,
    stddevPop(trip_duration) as std_trip_duration,
    stddevPop(trip_distance) as std_trip_distance,
    stddevPop(fare_amount) as std_fare_amount,
    stddevPop(tip_amount) as std_tip_amount,
    stddevPop(total_amount) as std_total_amount,
    varPop(trip_duration) as var_trip_duration,
    varPop(trip_distance) as var_trip_distance,
    varPop(fare_amount) as var_fare_amount,
    varPop(tip_amount) as var_tip_amount,
    varPop(total_amount) as var_total_amount,
    min(trip_duration) as min_trip_duration,
    min(trip_distance) as min_trip_distance,
    min(fare_amount) as min_fare_amount,
    min(tip_amount) as min_tip_amount,
    min(total_amount) as min_total_amount,
    max(trip_duration) as max_trip_duration,
    max(trip_distance) as max_trip_distance,
    max(fare_amount) as max_fare_amount,
    max(tip_amount) as max_tip_amount,
    max(total_amount) as max_total_amount,
    median(trip_duration) as median_trip_duration,
    median(trip_distance) as median_trip_distance,
    median(fare_amount) as median_fare_amount,
    median(tip_amount) as median_tip_amount,
    median(total_amount) as median_total_amount
from trips
group by toYear(pickup_datetime),
    toWeek(pickup_datetime),
    toDayOfWeek(pickup_datetime),
    toHour(pickup_datetime)
order by toYear(pickup_datetime),
    toWeek(pickup_datetime),
    toDayOfWeek(pickup_datetime),
    toHour(pickup_datetime);