-- feature of 1 hour window
WITH 
    (toDayOfYear(pickup_datetime) * 24 + toHour(pickup_datetime) ) AS pickup_hourstamp,
    (toDayOfYear(dropoff_datetime) * 24 + toHour(dropoff_datetime) ) AS dropoff_hourstamp,
    {hourstamp} AS target_hourstamp,
    pickup_hourstamp BETWEEN target_hourstamp - 1 AND target_hourstamp - 1 AS departed, 
    dropoff_hourstamp BETWEEN target_hourstamp - 1 AND target_hourstamp - 1 AS finished
SELECT count() AS count_departure_1h,
    avg(trip_duration) AS avg_trip_duration_1h,
    avg(trip_distance) AS avg_trip_distance_1h,
    avg(fare_amount) AS avg_fare_amount_1h,
    avg(tip_amount) AS avg_tip_amount_1h,
    avg(total_amount) AS avg_total_amount_1h,
    sum(trip_duration) AS sum_trip_duration_1h,
    sum(trip_distance) AS sum_trip_distance_1h,
    sum(fare_amount) AS sum_fare_amount_1h,
    sum(tip_amount) AS sum_tip_amount_1h,
    sum(total_amount) AS sum_total_amount_1h,
    stddevPop(trip_duration) AS std_trip_duration_1h,
    stddevPop(trip_distance) AS std_trip_distance_1h,
    stddevPop(fare_amount) AS std_fare_amount_1h,
    stddevPop(tip_amount) AS std_tip_amount_1h,
    stddevPop(total_amount) AS std_total_amount_1h,
    varPop(trip_duration) AS var_trip_duration_1h,
    varPop(trip_distance) AS var_trip_distance_1h,
    varPop(fare_amount) AS var_fare_amount_1h,
    varPop(tip_amount) AS var_tip_amount_1h,
    varPop(total_amount) AS var_total_amount_1h,
    min(trip_duration) AS min_trip_duration_1h,
    min(trip_distance) AS min_trip_distance_1h,
    min(fare_amount) AS min_fare_amount_1h,
    min(tip_amount) AS min_tip_amount_1h,
    min(total_amount) AS min_total_amount_1h,
    max(trip_duration) AS max_trip_duration_1h,
    max(trip_distance) AS max_trip_distance_1h,
    max(fare_amount) AS max_fare_amount_1h,
    max(tip_amount) AS max_tip_amount_1h,
    max(total_amount) AS max_total_amount_1h,
    median(trip_duration) AS median_trip_duration_1h,
    median(trip_distance) AS median_trip_distance_1h,
    median(fare_amount) AS median_fare_amount_1h,
    median(tip_amount) AS median_tip_amount_1h,
    median(total_amount) AS median_total_amount_1h,
    countIf(finished) AS count_departure_finished_1h,
    avgIf(trip_duration, finished) AS avg_trip_duration_finished_1h,
    avgIf(trip_distance, finished) AS avg_trip_distance_finished_1h,
    avgIf(fare_amount, finished) AS avg_fare_amount_finished_1h,
    avgIf(tip_amount, finished) AS avg_tip_amount_finished_1h,
    avgIf(total_amount, finished) AS avg_total_amount_finished_1h,
    sumIf(trip_duration, finished) AS sum_trip_duration_finished_1h,
    sumIf(trip_distance, finished) AS sum_trip_distance_finished_1h,
    sumIf(fare_amount, finished) AS sum_fare_amount_finished_1h,
    sumIf(tip_amount, finished) AS sum_tip_amount_finished_1h,
    sumIf(total_amount, finished) AS sum_total_amount_finished_1h,
    stddevPopIf(trip_duration, finished) AS std_trip_duration_finished_1h,
    stddevPopIf(trip_distance, finished) AS std_trip_distance_finished_1h,
    stddevPopIf(fare_amount, finished) AS std_fare_amount_finished_1h,
    stddevPopIf(tip_amount, finished) AS std_tip_amount_finished_1h,
    stddevPopIf(total_amount, finished) AS std_total_amount_finished_1h,
    varPopIf(trip_duration, finished) AS var_trip_duration_finished_1h,
    varPopIf(trip_distance, finished) AS var_trip_distance_finished_1h,
    varPopIf(fare_amount, finished) AS var_fare_amount_finished_1h,
    varPopIf(tip_amount, finished) AS var_tip_amount_finished_1h,
    varPopIf(total_amount, finished) AS var_total_amount_finished_1h,
    minIf(trip_duration, finished) AS min_trip_duration_finished_1h,
    minIf(trip_distance, finished) AS min_trip_distance_finished_1h,
    minIf(fare_amount, finished) AS min_fare_amount_finished_1h,
    minIf(tip_amount, finished) AS min_tip_amount_finished_1h,
    minIf(total_amount, finished) AS min_total_amount_finished_1h,
    maxIf(trip_duration, finished) AS max_trip_duration_finished_1h,
    maxIf(trip_distance, finished) AS max_trip_distance_finished_1h,
    maxIf(fare_amount, finished) AS max_fare_amount_finished_1h,
    maxIf(tip_amount, finished) AS max_tip_amount_finished_1h,
    maxIf(total_amount, finished) AS max_total_amount_finished_1h,
    medianIf(trip_duration, finished) AS median_trip_duration_finished_1h,
    medianIf(trip_distance, finished) AS median_trip_distance_finished_1h,
    medianIf(fare_amount, finished) AS median_fare_amount_finished_1h,
    medianIf(tip_amount, finished) AS median_tip_amount_finished_1h,
    medianIf(total_amount, finished) AS median_total_amount_finished_1h
FROM trips
WHERE departed;

-- feature of 24h window
WITH 
    (toDayOfYear(pickup_datetime) * 24 + toHour(pickup_datetime) ) AS pickup_hourstamp,
    (toDayOfYear(dropoff_datetime) * 24 + toHour(dropoff_datetime) ) AS dropoff_hourstamp,
    {hourstamp} AS target_hourstamp,
    pickup_hourstamp BETWEEN target_hourstamp - 24 AND target_hourstamp - 1 AS departed, 
    dropoff_hourstamp BETWEEN target_hourstamp - 24 AND target_hourstamp - 1 AS finished
SELECT count() AS count_departure_24h,
    avg(trip_duration) AS avg_trip_duration_24h,
    avg(trip_distance) AS avg_trip_distance_24h,
    avg(fare_amount) AS avg_fare_amount_24h,
    avg(tip_amount) AS avg_tip_amount_24h,
    avg(total_amount) AS avg_total_amount_24h,
    sum(trip_duration) AS sum_trip_duration_24h,
    sum(trip_distance) AS sum_trip_distance_24h,
    sum(fare_amount) AS sum_fare_amount_24h,
    sum(tip_amount) AS sum_tip_amount_24h,
    sum(total_amount) AS sum_total_amount_24h,
    stddevPop(trip_duration) AS std_trip_duration_24h,
    stddevPop(trip_distance) AS std_trip_distance_24h,
    stddevPop(fare_amount) AS std_fare_amount_24h,
    stddevPop(tip_amount) AS std_tip_amount_24h,
    stddevPop(total_amount) AS std_total_amount_24h,
    varPop(trip_duration) AS var_trip_duration_24h,
    varPop(trip_distance) AS var_trip_distance_24h,
    varPop(fare_amount) AS var_fare_amount_24h,
    varPop(tip_amount) AS var_tip_amount_24h,
    varPop(total_amount) AS var_total_amount_24h,
    min(trip_duration) AS min_trip_duration_24h,
    min(trip_distance) AS min_trip_distance_24h,
    min(fare_amount) AS min_fare_amount_24h,
    min(tip_amount) AS min_tip_amount_24h,
    min(total_amount) AS min_total_amount_24h,
    max(trip_duration) AS max_trip_duration_24h,
    max(trip_distance) AS max_trip_distance_24h,
    max(fare_amount) AS max_fare_amount_24h,
    max(tip_amount) AS max_tip_amount_24h,
    max(total_amount) AS max_total_amount_24h,
    median(trip_duration) AS median_trip_duration_24h,
    median(trip_distance) AS median_trip_distance_24h,
    median(fare_amount) AS median_fare_amount_24h,
    median(tip_amount) AS median_tip_amount_24h,
    median(total_amount) AS median_total_amount_24h,
    countIf(finished) AS count_departure_finished_24h,
    avgIf(trip_duration, finished) AS avg_trip_duration_finished_24h,
    avgIf(trip_distance, finished) AS avg_trip_distance_finished_24h,
    avgIf(fare_amount, finished) AS avg_fare_amount_finished_24h,
    avgIf(tip_amount, finished) AS avg_tip_amount_finished_24h,
    avgIf(total_amount, finished) AS avg_total_amount_finished_24h,
    sumIf(trip_duration, finished) AS sum_trip_duration_finished_24h,
    sumIf(trip_distance, finished) AS sum_trip_distance_finished_24h,
    sumIf(fare_amount, finished) AS sum_fare_amount_finished_24h,
    sumIf(tip_amount, finished) AS sum_tip_amount_finished_24h,
    sumIf(total_amount, finished) AS sum_total_amount_finished_24h,
    stddevPopIf(trip_duration, finished) AS std_trip_duration_finished_24h,
    stddevPopIf(trip_distance, finished) AS std_trip_distance_finished_24h,
    stddevPopIf(fare_amount, finished) AS std_fare_amount_finished_24h,
    stddevPopIf(tip_amount, finished) AS std_tip_amount_finished_24h,
    stddevPopIf(total_amount, finished) AS std_total_amount_finished_24h,
    varPopIf(trip_duration, finished) AS var_trip_duration_finished_24h,
    varPopIf(trip_distance, finished) AS var_trip_distance_finished_24h,
    varPopIf(fare_amount, finished) AS var_fare_amount_finished_24h,
    varPopIf(tip_amount, finished) AS var_tip_amount_finished_24h,
    varPopIf(total_amount, finished) AS var_total_amount_finished_24h,
    minIf(trip_duration, finished) AS min_trip_duration_finished_24h,
    minIf(trip_distance, finished) AS min_trip_distance_finished_24h,
    minIf(fare_amount, finished) AS min_fare_amount_finished_24h,
    minIf(tip_amount, finished) AS min_tip_amount_finished_24h,
    minIf(total_amount, finished) AS min_total_amount_finished_24h,
    maxIf(trip_duration, finished) AS max_trip_duration_finished_24h,
    maxIf(trip_distance, finished) AS max_trip_distance_finished_24h,
    maxIf(fare_amount, finished) AS max_fare_amount_finished_24h,
    maxIf(tip_amount, finished) AS max_tip_amount_finished_24h,
    maxIf(total_amount, finished) AS max_total_amount_finished_24h,
    medianIf(trip_duration, finished) AS median_trip_duration_finished_24h,
    medianIf(trip_distance, finished) AS median_trip_distance_finished_24h,
    medianIf(fare_amount, finished) AS median_fare_amount_finished_24h,
    medianIf(tip_amount, finished) AS median_tip_amount_finished_24h,
    medianIf(total_amount, finished) AS median_total_amount_finished_24h
FROM trips
WHERE departed;

-- feature of target hour of yesterday
WITH 
    (toDayOfYear(pickup_datetime) * 24 + toHour(pickup_datetime) ) AS pickup_hourstamp,
    (toDayOfYear(dropoff_datetime) * 24 + toHour(dropoff_datetime) ) AS dropoff_hourstamp,
    {hourstamp} AS target_hourstamp,
    pickup_hourstamp BETWEEN target_hourstamp - 24 AND target_hourstamp - 24 AS departed, 
    dropoff_hourstamp BETWEEN target_hourstamp - 24 AND target_hourstamp - 24 AS finished
SELECT count() AS count_departure_yesterday_1h,
    avg(trip_duration) AS avg_trip_duration_yesterday_1h,
    avg(trip_distance) AS avg_trip_distance_yesterday_1h,
    avg(fare_amount) AS avg_fare_amount_yesterday_1h,
    avg(tip_amount) AS avg_tip_amount_yesterday_1h,
    avg(total_amount) AS avg_total_amount_yesterday_1h,
    sum(trip_duration) AS sum_trip_duration_yesterday_1h,
    sum(trip_distance) AS sum_trip_distance_yesterday_1h,
    sum(fare_amount) AS sum_fare_amount_yesterday_1h,
    sum(tip_amount) AS sum_tip_amount_yesterday_1h,
    sum(total_amount) AS sum_total_amount_yesterday_1h,
    stddevPop(trip_duration) AS std_trip_duration_yesterday_1h,
    stddevPop(trip_distance) AS std_trip_distance_yesterday_1h,
    stddevPop(fare_amount) AS std_fare_amount_yesterday_1h,
    stddevPop(tip_amount) AS std_tip_amount_yesterday_1h,
    stddevPop(total_amount) AS std_total_amount_yesterday_1h,
    varPop(trip_duration) AS var_trip_duration_yesterday_1h,
    varPop(trip_distance) AS var_trip_distance_yesterday_1h,
    varPop(fare_amount) AS var_fare_amount_yesterday_1h,
    varPop(tip_amount) AS var_tip_amount_yesterday_1h,
    varPop(total_amount) AS var_total_amount_yesterday_1h,
    min(trip_duration) AS min_trip_duration_yesterday_1h,
    min(trip_distance) AS min_trip_distance_yesterday_1h,
    min(fare_amount) AS min_fare_amount_yesterday_1h,
    min(tip_amount) AS min_tip_amount_yesterday_1h,
    min(total_amount) AS min_total_amount_yesterday_1h,
    max(trip_duration) AS max_trip_duration_yesterday_1h,
    max(trip_distance) AS max_trip_distance_yesterday_1h,
    max(fare_amount) AS max_fare_amount_yesterday_1h,
    max(tip_amount) AS max_tip_amount_yesterday_1h,
    max(total_amount) AS max_total_amount_yesterday_1h,
    median(trip_duration) AS median_trip_duration_yesterday_1h,
    median(trip_distance) AS median_trip_distance_yesterday_1h,
    median(fare_amount) AS median_fare_amount_yesterday_1h,
    median(tip_amount) AS median_tip_amount_yesterday_1h,
    median(total_amount) AS median_total_amount_yesterday_1h,
    countIf(finished) AS count_departure_finished_yesterday_1h,
    avgIf(trip_duration, finished) AS avg_trip_duration_finished_yesterday_1h,
    avgIf(trip_distance, finished) AS avg_trip_distance_finished_yesterday_1h,
    avgIf(fare_amount, finished) AS avg_fare_amount_finished_yesterday_1h,
    avgIf(tip_amount, finished) AS avg_tip_amount_finished_yesterday_1h,
    avgIf(total_amount, finished) AS avg_total_amount_finished_yesterday_1h,
    sumIf(trip_duration, finished) AS sum_trip_duration_finished_yesterday_1h,
    sumIf(trip_distance, finished) AS sum_trip_distance_finished_yesterday_1h,
    sumIf(fare_amount, finished) AS sum_fare_amount_finished_yesterday_1h,
    sumIf(tip_amount, finished) AS sum_tip_amount_finished_yesterday_1h,
    sumIf(total_amount, finished) AS sum_total_amount_finished_yesterday_1h,
    stddevPopIf(trip_duration, finished) AS std_trip_duration_finished_yesterday_1h,
    stddevPopIf(trip_distance, finished) AS std_trip_distance_finished_yesterday_1h,
    stddevPopIf(fare_amount, finished) AS std_fare_amount_finished_yesterday_1h,
    stddevPopIf(tip_amount, finished) AS std_tip_amount_finished_yesterday_1h,
    stddevPopIf(total_amount, finished) AS std_total_amount_finished_yesterday_1h,
    varPopIf(trip_duration, finished) AS var_trip_duration_finished_yesterday_1h,
    varPopIf(trip_distance, finished) AS var_trip_distance_finished_yesterday_1h,
    varPopIf(fare_amount, finished) AS var_fare_amount_finished_yesterday_1h,
    varPopIf(tip_amount, finished) AS var_tip_amount_finished_yesterday_1h,
    varPopIf(total_amount, finished) AS var_total_amount_finished_yesterday_1h,
    minIf(trip_duration, finished) AS min_trip_duration_finished_yesterday_1h,
    minIf(trip_distance, finished) AS min_trip_distance_finished_yesterday_1h,
    minIf(fare_amount, finished) AS min_fare_amount_finished_yesterday_1h,
    minIf(tip_amount, finished) AS min_tip_amount_finished_yesterday_1h,
    minIf(total_amount, finished) AS min_total_amount_finished_yesterday_1h,
    maxIf(trip_duration, finished) AS max_trip_duration_finished_yesterday_1h,
    maxIf(trip_distance, finished) AS max_trip_distance_finished_yesterday_1h,
    maxIf(fare_amount, finished) AS max_fare_amount_finished_yesterday_1h,
    maxIf(tip_amount, finished) AS max_tip_amount_finished_yesterday_1h,
    maxIf(total_amount, finished) AS max_total_amount_finished_yesterday_1h,
    medianIf(trip_duration, finished) AS median_trip_duration_finished_yesterday_1h,
    medianIf(trip_distance, finished) AS median_trip_distance_finished_yesterday_1h,
    medianIf(fare_amount, finished) AS median_fare_amount_finished_yesterday_1h,
    medianIf(tip_amount, finished) AS median_tip_amount_finished_yesterday_1h,
    medianIf(total_amount, finished) AS median_total_amount_finished_yesterday_1h
FROM trips
WHERE departed;

-- feature of target hour of last week
WITH 
    (toDayOfYear(pickup_datetime) * 24 + toHour(pickup_datetime) ) AS pickup_hourstamp,
    (toDayOfYear(dropoff_datetime) * 24 + toHour(dropoff_datetime) ) AS dropoff_hourstamp,
    {hourstamp} AS target_hourstamp,
    pickup_hourstamp BETWEEN target_hourstamp - 24 * 7 AND target_hourstamp - 24 * 7 AS departed, 
    dropoff_hourstamp BETWEEN target_hourstamp - 24 * 7 AND target_hourstamp - 24 * 7 AS finished
SELECT count() AS count_departure_last_week_1h,
    avg(trip_duration) AS avg_trip_duration_last_week_1h,
    avg(trip_distance) AS avg_trip_distance_last_week_1h,
    avg(fare_amount) AS avg_fare_amount_last_week_1h,
    avg(tip_amount) AS avg_tip_amount_last_week_1h,
    avg(total_amount) AS avg_total_amount_last_week_1h,
    sum(trip_duration) AS sum_trip_duration_last_week_1h,
    sum(trip_distance) AS sum_trip_distance_last_week_1h,
    sum(fare_amount) AS sum_fare_amount_last_week_1h,
    sum(tip_amount) AS sum_tip_amount_last_week_1h,
    sum(total_amount) AS sum_total_amount_last_week_1h,
    stddevPop(trip_duration) AS std_trip_duration_last_week_1h,
    stddevPop(trip_distance) AS std_trip_distance_last_week_1h,
    stddevPop(fare_amount) AS std_fare_amount_last_week_1h,
    stddevPop(tip_amount) AS std_tip_amount_last_week_1h,
    stddevPop(total_amount) AS std_total_amount_last_week_1h,
    varPop(trip_duration) AS var_trip_duration_last_week_1h,
    varPop(trip_distance) AS var_trip_distance_last_week_1h,
    varPop(fare_amount) AS var_fare_amount_last_week_1h,
    varPop(tip_amount) AS var_tip_amount_last_week_1h,
    varPop(total_amount) AS var_total_amount_last_week_1h,
    min(trip_duration) AS min_trip_duration_last_week_1h,
    min(trip_distance) AS min_trip_distance_last_week_1h,
    min(fare_amount) AS min_fare_amount_last_week_1h,
    min(tip_amount) AS min_tip_amount_last_week_1h,
    min(total_amount) AS min_total_amount_last_week_1h,
    max(trip_duration) AS max_trip_duration_last_week_1h,
    max(trip_distance) AS max_trip_distance_last_week_1h,
    max(fare_amount) AS max_fare_amount_last_week_1h,
    max(tip_amount) AS max_tip_amount_last_week_1h,
    max(total_amount) AS max_total_amount_last_week_1h,
    median(trip_duration) AS median_trip_duration_last_week_1h,
    median(trip_distance) AS median_trip_distance_last_week_1h,
    median(fare_amount) AS median_fare_amount_last_week_1h,
    median(tip_amount) AS median_tip_amount_last_week_1h,
    median(total_amount) AS median_total_amount_last_week_1h,
    countIf(finished) AS count_departure_finished_last_week_1h,
    avgIf(trip_duration, finished) AS avg_trip_duration_finished_last_week_1h,
    avgIf(trip_distance, finished) AS avg_trip_distance_finished_last_week_1h,
    avgIf(fare_amount, finished) AS avg_fare_amount_finished_last_week_1h,
    avgIf(tip_amount, finished) AS avg_tip_amount_finished_last_week_1h,
    avgIf(total_amount, finished) AS avg_total_amount_finished_last_week_1h,
    sumIf(trip_duration, finished) AS sum_trip_duration_finished_last_week_1h,
    sumIf(trip_distance, finished) AS sum_trip_distance_finished_last_week_1h,
    sumIf(fare_amount, finished) AS sum_fare_amount_finished_last_week_1h,
    sumIf(tip_amount, finished) AS sum_tip_amount_finished_last_week_1h,
    sumIf(total_amount, finished) AS sum_total_amount_finished_last_week_1h,
    stddevPopIf(trip_duration, finished) AS std_trip_duration_finished_last_week_1h,
    stddevPopIf(trip_distance, finished) AS std_trip_distance_finished_last_week_1h,
    stddevPopIf(fare_amount, finished) AS std_fare_amount_finished_last_week_1h,
    stddevPopIf(tip_amount, finished) AS std_tip_amount_finished_last_week_1h,
    stddevPopIf(total_amount, finished) AS std_total_amount_finished_last_week_1h,
    varPopIf(trip_duration, finished) AS var_trip_duration_finished_last_week_1h,
    varPopIf(trip_distance, finished) AS var_trip_distance_finished_last_week_1h,
    varPopIf(fare_amount, finished) AS var_fare_amount_finished_last_week_1h,
    varPopIf(tip_amount, finished) AS var_tip_amount_finished_last_week_1h,
    varPopIf(total_amount, finished) AS var_total_amount_finished_last_week_1h,
    minIf(trip_duration, finished) AS min_trip_duration_finished_last_week_1h,
    minIf(trip_distance, finished) AS min_trip_distance_finished_last_week_1h,
    minIf(fare_amount, finished) AS min_fare_amount_finished_last_week_1h,
    minIf(tip_amount, finished) AS min_tip_amount_finished_last_week_1h,
    minIf(total_amount, finished) AS min_total_amount_finished_last_week_1h,
    maxIf(trip_duration, finished) AS max_trip_duration_finished_last_week_1h,
    maxIf(trip_distance, finished) AS max_trip_distance_finished_last_week_1h,
    maxIf(fare_amount, finished) AS max_fare_amount_finished_last_week_1h,
    maxIf(tip_amount, finished) AS max_tip_amount_finished_last_week_1h,
    maxIf(total_amount, finished) AS max_total_amount_finished_last_week_1h,
    medianIf(trip_duration, finished) AS median_trip_duration_finished_last_week_1h,
    medianIf(trip_distance, finished) AS median_trip_distance_finished_last_week_1h,
    medianIf(fare_amount, finished) AS median_fare_amount_finished_last_week_1h,
    medianIf(tip_amount, finished) AS median_tip_amount_finished_last_week_1h,
    medianIf(total_amount, finished) AS median_total_amount_finished_last_week_1h
FROM trips
WHERE departed;
