python extract_apx_features.py --sampling_rate 0.001
python extract_apx_features.py --sampling_rate 0.01
python extract_apx_features.py --sampling_rate 0.05
python extract_apx_features.py --sampling_rate 0.1
python extract_apx_features.py --sampling_rate 0.2
python extract_apx_features.py --sampling_rate 0.3
python extract_apx_features.py --sampling_rate 0.4
python extract_apx_features.py --sampling_rate 0.5
python extract_apx_features.py --sampling_rate 0.6
python extract_apx_features.py --sampling_rate 0.7
python extract_apx_features.py --sampling_rate 0.8
python extract_apx_features.py --sampling_rate 0.9
python extract_apx_features.py --sampling_rate 1.0
